# .../profiles/config.yaml

# Execute the pipeline using SLURM 
executor: slurm
jobs: 100

# Let Snakemake calculate default resources unless specified in rule
default-resources:
  slurm_partition: "cmp"
  runtime: 60
  mem_mb: 4000

# Path to our config file specifying samples to process
configfile: samples.yaml

# Misc flags
printshellcmds: true
show-failed-logs: true
